# Generated by Django 6.0.6 on 2026-08-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="ชื่อประเภทคำถาม"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        max_length=20,
                        verbose_name="รหัสสี HEX (สำหรับกราฟ/ป้าย)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
            ],
            options={
                "verbose_name": "ประเภทคำถาม",
                "verbose_name_plural": "ประเภทคำถามทั้งหมด",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="ข้อความคำถาม")),
                ("choice_a", models.CharField(max_length=255, verbose_name="ตัวเลือก A")),
                ("choice_b", models.CharField(max_length=255, verbose_name="ตัวเลือก B")),
                ("choice_c", models.CharField(max_length=255, verbose_name="ตัวเลือก C")),
                ("choice_d", models.CharField(max_length=255, verbose_name="ตัวเลือก D")),
                (
                    "correct_choice",
                    models.CharField(
                        choices=[
                            ("A", "ตัวเลือก A"),
                            ("B", "ตัวเลือก B"),
                            ("C", "ตัวเลือก C"),
                            ("D", "ตัวเลือก D"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="คำตอบที่ถูกต้อง",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="คำอธิบายเฉลย"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("ง่าย", "ง่าย"),
                            ("ปานกลาง", "ปานกลาง"),
                            ("ยาก", "ยาก"),
                        ],
                        default="ง่าย",
                        max_length=20,
                        verbose_name="ระดับความยาก",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="my_app.category",
                        verbose_name="ประเภทคำถาม",
                    ),
                ),
            ],
            options={
                "verbose_name": "คำถาม",
                "verbose_name_plural": "คำถามทั้งหมด",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QuizLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "played_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลาที่เล่น"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="ตอบถูกต้องหรือไม่"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="my_app.question",
                        verbose_name="คำถามที่เล่น",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติการสุ่มคำถาม",
                "verbose_name_plural": "ประวัติการสุ่มคำถามทั้งหมด",
                "ordering": ["-played_at"],
            },
        ),
    ]
