from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from my_app.models import Category, Question, QuizLog


class Command(BaseCommand):
    help = "ล้างข้อมูลเก่าและสร้างชุดคำถามใหม่ 50 ข้อ ระดับง่ายมาก (Super Easy & Fun) ตอบได้ทุกคน"

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.NOTICE("Reseeding 50 super easy and fun questions..."))

        # ล้างข้อมูลคำถามและประวัติเก่าทั้งหมด
        QuizLog.objects.all().delete()
        Question.objects.all().delete()
        Category.objects.all().delete()
        self.stdout.write(self.style.WARNING("[RESET] Cleared old QuizLogs, Questions, and Categories"))

        # 1. บัญชี Admin
        if not User.objects.filter(username="admin").exists():
            User.objects.create_superuser("admin", "admin@csquiz.local", "admin1234")
            self.stdout.write(self.style.SUCCESS("[OK] Admin user ready: admin / admin1234"))

        # 2. สร้าง 2 หมวดหมู่หลัก
        cat_basic = Category.objects.create(
            name="คอมพิวเตอร์และไอทีแสนสนุก",
            color="#0ea5e9"  # สีฟ้าสดใส
        )
        cat_cs = Category.objects.create(
            name="ความรู้รอบตัวและโลกดิจิทัล",
            color="#8b5cf6"  # สีม่วงเทคโนโลยี
        )
        self.stdout.write(self.style.SUCCESS("[OK] Created 2 categories"))

        # 3. ชุดคำถาม 50 ข้อ ระดับง่ายมาก สนุก ตอบได้ทุกคน
        questions = [
            {
                "category": cat_basic,
                "text": "อุปกรณ์ใดมีหน้าตาเหมือน 'หนู' ใช้เลื่อนลูกศรบนหน้าจอคอมพิวเตอร์?",
                "choice_a": "เมาส์ (Mouse)",
                "choice_b": "แมว",
                "choice_c": "สุนัข",
                "choice_d": "ช้าง",
                "correct_choice": "A",
                "explanation": "เมาส์ (Mouse) ภาษาอังกฤษแปลว่าหนู ใช้สำหรับเลื่อนเคอร์เซอร์และคลิกเลือกสิ่งต่าง ๆ บนหน้าจอ",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "ถ้าต้องการพิมพ์ชื่อของตัวเองลงในคอมพิวเตอร์ น้อง ๆ ต้องใช้อุปกรณ์ใด?",
                "choice_a": "คีย์บอร์ด หรือ แป้นพิมพ์ (Keyboard)",
                "choice_b": "ไม้กวาด",
                "choice_c": "รองเท้าแตะ",
                "choice_d": "ช้อนส้อม",
                "correct_choice": "A",
                "explanation": "คีย์บอร์ดมีปุ่มตัวอักษร ก-ฮ และ A-Z ใช้สำหรับพิมพ์ข้อความเข้าสู่คอมพิวเตอร์",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "ข้อใดคือปุ่มสำหรับ 'เคาะเว้นวรรค' ที่มีขนาดยาวที่สุดบนคีย์บอร์ด?",
                "choice_a": "Spacebar (สเปซบาร์)",
                "choice_b": "ปุ่มเปิดแอร์",
                "choice_c": "ปุ่มกดน้ำดื่ม",
                "choice_d": "ปุ่มเบรกรถยนต์",
                "correct_choice": "A",
                "explanation": "Spacebar เป็นปุ่มยาวที่สุด อยู่แถวล่างสุดของคีย์บอร์ด ใช้สำหรับเว้นวรรคตัวหนังสือ",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "ถ้าเรากดปุ่ม 'Enter' บนคีย์บอร์ด จะเกิดอะไรขึ้นในการพิมพ์ข้อความ?",
                "choice_a": "ขึ้นบรรทัดใหม่ หรือ กดยืนยัน",
                "choice_b": "คอมพิวเตอร์บินได้",
                "choice_c": "ไฟดับทั้งบ้าน",
                "choice_d": "หน้าจอกลายเป็นสีรุ้ง",
                "correct_choice": "A",
                "explanation": "ปุ่ม Enter ใช้สำหรับขึ้นบรรทัดใหม่ในการพิมพ์งาน หรือกดยืนยันตกลง",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "อุปกรณ์ใดทำหน้าที่ฉายภาพ การ์ตูน หรือเกมให้เรามองเห็นด้วยตา?",
                "choice_a": "จอภาพ (Monitor)",
                "choice_b": "เครื่องซักผ้า",
                "choice_c": "หม้อหุงข้าว",
                "choice_d": "เตารีด",
                "correct_choice": "A",
                "explanation": "จอภาพทำหน้าที่แสดงผลภาพกราฟิก วิดีโอ และตัวหนังสือให้เรามองเห็น",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "หากต้องการฟังเพลงหรือเสียงเกมจากคอมพิวเตอร์คนเดียวโดยไม่รบกวนผู้อื่น ควรใช้อุปกรณ์ใด?",
                "choice_a": "หูฟัง (Headphones)",
                "choice_b": "แว่นตากันแดด",
                "choice_c": "หน้ากากอนามัย",
                "choice_d": "หมวกกันน็อค",
                "correct_choice": "A",
                "explanation": "หูฟังช่วยส่งเสียงเข้าสู่หูของเราโดยตรง ไม่ส่งเสียงดังรบกวนคนรอบข้าง",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "แอปพลิเคชันใดที่มีไอคอนสีแดงรูปปุ่ม Play ▶ ใช้สำหรับดูคลิปวิดีโอและการ์ตูน?",
                "choice_a": "YouTube (ยูทูบ)",
                "choice_b": "เครื่องคิดเลข",
                "choice_c": "นาฬิกาปลุก",
                "choice_d": "สมุดโทรศัพท์",
                "correct_choice": "A",
                "explanation": "YouTube เป็นแหล่งรวมคลิปวิดีโอ การ์ตูน เพลง และสาระความรู้ยอดนิยมของคนทั่วโลก",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "หากต้องการค้นหาข้อมูลหรือภาพสวย ๆ บนอินเทอร์เน็ต นิยมเข้าเว็บไซต์ใดมากที่สุด?",
                "choice_a": "Google (กูเกิล)",
                "choice_b": "ร้านขายยา",
                "choice_c": "ปั๊มน้ำมัน",
                "choice_d": "สนามบิน",
                "correct_choice": "A",
                "explanation": "Google เป็นเครื่องมือค้นหา (Search Engine) อันดับ 1 ที่ค้นหาคำตอบได้เกือบทุกอย่างบนโลก",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "ปุ่มลัดสุดฮิต 'Ctrl + C' บนคีย์บอร์ด ใช้สำหรับคำสั่งอะไร?",
                "choice_a": "คัดลอก (Copy)",
                "choice_b": "ปิดเครื่องทันที",
                "choice_c": "ล้างจาน",
                "choice_d": "รดน้ำต้นไม้",
                "correct_choice": "A",
                "explanation": "Ctrl + C ย่อมาจาก Copy ใช้คัดลอกข้อความ รูปภาพ หรือไฟล์งานได้อย่างรวดเร็ว",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "ปุ่มลัด 'Ctrl + V' นิยมใช้คู่กับ Ctrl + C เพื่อทำหน้าที่อะไร?",
                "choice_a": "วางข้อความหรือรูปภาพ (Paste)",
                "choice_b": "ถ่ายรูปหน้าจอ",
                "choice_c": "ซักผ้า",
                "choice_d": "กวาดบ้าน",
                "correct_choice": "A",
                "explanation": "Ctrl + V ใช้สั่งวาง (Paste) สิ่งที่เราคัดลอกไว้ลงในตำแหน่งที่ต้องการ",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "ข้อใดคือสิ่งที่ไม่ควรทำเมื่อมีคนแปลกหน้าทักแชทมาขอรหัสผ่าน (Password)?",
                "choice_a": "รีบส่งรหัสผ่านให้เขาทันที",
                "choice_b": "รีบปรึกษาคุณครูหรือผู้ปกครอง",
                "choice_c": "กดบล็อกคนแปลกหน้า",
                "choice_d": "ไม่ตอบข้อความของคนแปลกหน้า",
                "correct_choice": "A",
                "explanation": "รหัสผ่านเป็นความลับส่วนตัว ห้ามบอกคนแปลกหน้าเด็ดขาดเพื่อป้องกันมิจฉาชีพ",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "ไอคอนรูป 'ถังขยะ' 🗑️ (Recycle Bin) บนหน้าจอคอมพิวเตอร์ มีไว้ทำอะไร?",
                "choice_a": "เก็บไฟล์เอกสารหรือรูปภาพที่เราลบทิ้ง",
                "choice_b": "ทิ้งเปลือกกล้วยและเศษอาหารจริง",
                "choice_c": "ล้างมือ",
                "choice_d": "ทิ้งขวดน้ำพลาสติก",
                "correct_choice": "A",
                "explanation": "Recycle Bin เก็บไฟล์ที่เรากดลบไว้ชั่วคราว หากเปลี่ยนใจสามารถกดกู้คืนกลับมาได้",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "สัญญาณ Wi-Fi (ไวไฟ) มีประโยชน์อย่างไรในชีวิตประจำวันของเรา?",
                "choice_a": "เชื่อมต่ออินเทอร์เน็ตแบบไร้สาย ไม่ต้องเสียบสายแลน",
                "choice_b": "ต้มน้ำร้อนชงโอวัลติน",
                "choice_c": "ทำความเย็นในตู้เย็น",
                "choice_d": "เติมลมยางรถจักรยาน",
                "correct_choice": "A",
                "explanation": "Wi-Fi ช่วยให้อุปกรณ์มือถือ โน้ตบุ๊ก แท็บเล็ต ใช้งานอินเทอร์เน็ตได้สะดวกทุกที่",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "เจ้าแมวสีส้มในโปรแกรม 'Scratch' มีไว้สำหรับกิจกรรมใดของเด็ก ๆ?",
                "choice_a": "ฝึกเขียนโปรแกรมและสร้างเกมง่าย ๆ ด้วยบล็อกคำสั่ง",
                "choice_b": "ร้องเพลงโอเปร่า",
                "choice_c": "จับหนูในครัว",
                "choice_d": "นวดแป้งทำขนมปัง",
                "correct_choice": "A",
                "explanation": "Scratch ออกแบบมาเพื่อให้เด็ก ๆ เริ่มต้นเรียนรู้การเขียนโค้ดและสร้างเกมได้อย่างสนุกสนาน",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "เวลาเลิกใช้งานคอมพิวเตอร์แล้ว ข้อใดคือวิธีปิดเครื่องที่ถูกต้องและปลอดภัยที่สุด?",
                "choice_a": "คลิกปุ่ม Start แล้วเลือก Shut Down",
                "choice_b": "ดึงปลั๊กไฟบ้านออกแรง ๆ ทันที",
                "choice_c": "เอาน้ำเย็นมาราดใส่คอมพิวเตอร์",
                "choice_d": "เอากระดาษหนังสือพิมพ์มาปิดหน้าจอไว้",
                "correct_choice": "A",
                "explanation": "การกด Shut Down ช่วยให้ระบบเซฟไฟล์งานเรียบร้อยและรักษาเครื่องให้ใช้งานได้นาน ๆ",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "หน้าจอสมาร์ตโฟนและแท็บเล็ต เราสั่งงานด้วยวิธีใด?",
                "choice_a": "ใช้นิ้วมือสัมผัสแตะบนหน้าจอ (Touchscreen)",
                "choice_b": "เอาปลายจมูกไปแตะ",
                "choice_c": "กระโดดตบ 10 ครั้ง",
                "choice_d": "ตะโกนใส่หน้าจอ",
                "correct_choice": "A",
                "explanation": "หน้าจอสัมผัส (Touchscreen) รับคำสั่งจากการแตะ ปัด หรือลากนิ้วมือของเราได้อย่างง่ายดาย",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "หุ่นยนต์สามารถเดินหน้า เลี้ยวซ้าย หรือเต้นได้ เพราะมีสิ่งใดควบคุมอยู่ข้างใน?",
                "choice_a": "โปรแกรมหรือโค้ดคำสั่งที่โปรแกรมเมอร์เขียนขึ้น",
                "choice_b": "ข้าวเหนียวหมูปิ้ง",
                "choice_c": "น้ำส้มคั้น",
                "choice_d": "ใบตอง",
                "correct_choice": "A",
                "explanation": "หุ่นยนต์และสมองกลทุกตัวทำงานตามชุดคำสั่ง (Code) ที่มนุษย์เขียนป้อนเข้าไป",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "ภาษาคอมพิวเตอร์ยอดฮิตของโลกที่มีชื่อและโลโก้เหมือน 'งู' คือภาษาใด?",
                "choice_a": "Python (ไพทอน)",
                "choice_b": "งูเขียวหางไหม้",
                "choice_c": "งูจงอาง",
                "choice_d": "งูเหลือม",
                "correct_choice": "A",
                "explanation": "ภาษา Python (ไพทอน) เป็นภาษาโปรแกรมที่เขียนง่าย เข้าใจง่าย และใช้สร้าง AI ระดับโลก",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "คนที่ทำหน้าที่เขียนโค้ดและสร้างเกมสนุก ๆ ในคอมพิวเตอร์ เรียกว่าอะไร?",
                "choice_a": "โปรแกรมเมอร์ (Programmer)",
                "choice_b": "ช่างตัดเย็บเสื้อผ้า",
                "choice_c": "คนขับรถไฟความเร็วสูง",
                "choice_d": "นักประดาน้ำ",
                "correct_choice": "A",
                "explanation": "โปรแกรมเมอร์คือผู้สร้างสรรค์แอปพลิเคชัน เว็บไซต์ และเกมที่เราเล่นกันทุกวัน",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "แว่น 'VR' (Virtual Reality) เมื่อสวมใส่แล้วเราจะมองเห็นภาพแบบใด?",
                "choice_a": "ภาพ 3 มิติเสมือนจริงรอบตัว 360 องศา เหมือนอยู่ในเกมจริง ๆ",
                "choice_b": "ภาพมืดสนิทมองไม่เห็นอะไรเลย",
                "choice_c": "ภาพกลับหัวกลับหาง",
                "choice_d": "ภาพขาวดำเหมือนทีวีโบราณ",
                "correct_choice": "A",
                "explanation": "แว่น VR จำลองภาพ 3 มิติรอบทิศทาง ทำให้เรารู้สึกเหมือนได้เข้าไปอยู่ในโลกเสมือนจริง",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "สิ่งใดช่วยชาร์จพลังงานให้โน้ตบุ๊กหรือโทรศัพท์มือถือเมื่อแบตเตอรี่หมด?",
                "choice_a": "สายชาร์จแบตเตอรี่ (Charger)",
                "choice_b": "หลอดดูดน้ำพลาสติก",
                "choice_c": "เชือกฟาง",
                "choice_d": "สายสะพายกระเป๋า",
                "correct_choice": "A",
                "explanation": "สายชาร์จจะส่งกระแสไฟฟ้าเข้าไปเติมพลังงานในแบตเตอรี่ให้อุปกรณ์กลับมาใช้งานได้",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "ปุ่ม 'Backspace' บนคีย์บอร์ด ใช้ทำหน้าที่อะไรเมื่อเราพิมพ์ข้อความผิด?",
                "choice_a": "ลบตัวหนังสือที่พิมพ์ผิดออกทีละตัว",
                "choice_b": "ใส่รูปหัวใจสีชมพู",
                "choice_c": "เปลี่ยนสีพื้นหลังหน้าจอ",
                "choice_d": "เพิ่มเสียงลำโพงให้ดังขึ้น",
                "correct_choice": "A",
                "explanation": "ปุ่ม Backspace อยู่เหนือปุ่ม Enter ใช้กดเพื่อลบตัวอักษรที่พิมพ์ผิดได้อย่างง่ายดาย",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "สัญลักษณ์รูป 'แว่นขยาย' 🔍 ในแอปพลิเคชันต่าง ๆ หมายถึงคำสั่งอะไร?",
                "choice_a": "ค้นหาข้อมูล (Search)",
                "choice_b": "ส่องดูดาวบนท้องฟ้า",
                "choice_c": "ส่องพระเครื่อง",
                "choice_d": "จุดไฟเผากระดาษ",
                "correct_choice": "A",
                "explanation": "ไอคอนแว่นขยายเป็นสัญลักษณ์สากลที่หมายถึงการค้นหา (Search) รูป เพลง หรือข้อความ",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "สติกเกอร์รูป 👍 (ยกนิ้วโป้ง) บน Facebook หรือ YouTube หมายถึงอะไร?",
                "choice_a": "กดถูกใจ หรือ ชื่นชอบ (Like)",
                "choice_b": "โกรธมาก",
                "choice_c": "ง่วงนอนอยากพักผ่อน",
                "choice_d": "หิวน้ำมาก",
                "correct_choice": "A",
                "explanation": "การกด Like รูปนิ้วโป้ง เป็นการแสดงความรู้สึกชื่นชอบและให้กำลังใจเจ้าของคลิปหรือโพสต์",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_basic,
                "text": "กล้องเว็บแคม (Webcam) บนคอมพิวเตอร์มีประโยชน์หลักอย่างไร?",
                "choice_a": "ถ่ายทอดภาพใบหน้าของเราขณะเรียนออนไลน์หรือวิดีโอคอล",
                "choice_b": "ฉายแสงเลเซอร์ตัดเหล็ก",
                "choice_c": "วัดอุณหภูมิห้อง",
                "choice_d": "ส่งเสียงดนตรีออกมา",
                "correct_choice": "A",
                "explanation": "Webcam ช่วยจับภาพใบหน้าของเราส่งไปยังเพื่อนหรือคุณครูเวลาเรียนออนไลน์ผ่านเน็ต",
                "difficulty": "ง่าย",
                "is_active": True,
            },

            # ==========================================
            # 25 ข้อหลัง: ความรู้รอบตัวและโลกดิจิทัลแสนสนุก
            # ==========================================
            {
                "category": cat_cs,
                "text": "ในเกมยอดฮิตอย่าง Minecraft ผู้เล่นนิยมทำกิจกรรมใดเป็นหลัก?",
                "choice_a": "ขุดบล็อก ต่อบล็อกสร้างบ้าน และผจญภัย",
                "choice_b": "ซักผ้าด้วยผงซักฟอก",
                "choice_c": "รีดชุดนักเรียน",
                "choice_d": "ล้างจานชามในครัว",
                "correct_choice": "A",
                "explanation": "Minecraft เป็นเกมแนว Sandbox ที่ให้อิสระในการขุดและวางบล็อกสร้างสิ่งก่อสร้างตามจินตนาการ",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "เมื่อเราคลิกเมาส์ปุ่มซ้าย 2 ครั้งติดกันเร็ว ๆ ในคอมพิวเตอร์ เรียกว่าอะไร?",
                "choice_a": "ดับเบิลคลิก (Double Click) เพื่อเปิดไฟล์หรือแอป",
                "choice_b": "ทริปเปิลจั๊มพ์",
                "choice_c": "ซูเปอร์คิก",
                "choice_d": "การเต้นแท็ป",
                "correct_choice": "A",
                "explanation": "Double Click คือการคลิกเมาส์ 2 ครั้งติดกันอย่างรวดเร็ว เพื่อเปิดโฟลเดอร์หรือเปิดโปรแกรม",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ถ้าคอมพิวเตอร์ไม่มี 'จอภาพ' จะเกิดผลอย่างไรกับผู้ใช้งาน?",
                "choice_a": "เราจะมองไม่เห็นภาพอะไรเลยและใช้งานไม่ได้",
                "choice_b": "คอมพิวเตอร์จะเปิดใช้งานได้ตามปกติ",
                "choice_c": "คอมพิวเตอร์จะพูดคุยกับเราได้เอง",
                "choice_d": "ภาพจะลอยออกมาในอากาศรอบห้อง",
                "correct_choice": "A",
                "explanation": "จอภาพเป็นอุปกรณ์ส่งออกภาพหลัก หากไม่มีจอ เราจะไม่สามารถมองเห็นหน้าจอการทำงานได้",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "อุปกรณ์ขนาดเล็กชนิดใดใช้เสียบช่อง USB เพื่อพกพาไฟล์รูปภาพและเพลงไปเปิดเครื่องอื่น?",
                "choice_a": "แฟลชไดรฟ์ (Flash Drive)",
                "choice_b": "ตู้เสื้อผ้าไม้สัก",
                "choice_c": "โต๊ะกินข้าว",
                "choice_d": "กระถางต้นไม้",
                "correct_choice": "A",
                "explanation": "Flash Drive มีขนาดจิ๋วพกพาสะดวก เสียบเข้าช่อง USB เพื่อย้ายไฟล์งานได้ทันที",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "โปรแกรม Paint ในเครื่องคอมพิวเตอร์ มีไว้ให้เราทำอะไรอย่างสนุกสนาน?",
                "choice_a": "วาดรูปและระบายสีด้วยพู่กัน ดินสอ ถังสี",
                "choice_b": "ต้มบะหมี่กึ่งสำเร็จรูป",
                "choice_c": "ซ่อมโซ่จักรยาน",
                "choice_d": "ฟังคลื่นวิทยุ AM",
                "correct_choice": "A",
                "explanation": "Paint เป็นโปรแกรมวาดภาพที่มีเครื่องมือระบายสี ถังเทสี และรูปทรงเรขาคณิตครบครัน",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ถ้าต้องการพิมพ์ตัวเลข 1 2 3 บนคอมพิวเตอร์ เราต้องกดปุ่มที่อุปกรณ์ใด?",
                "choice_a": "แป้นพิมพ์ หรือ คีย์บอร์ด (Keyboard)",
                "choice_b": "ปลั๊กไฟบ้าน",
                "choice_c": "ลำโพงบลูทูธ",
                "choice_d": "พัดลมตั้งโต๊ะ",
                "correct_choice": "A",
                "explanation": "คีย์บอร์ดมีแป้นตัวเลข 0-9 ให้เรากดพิมพ์ตัวเลขได้อย่างสะดวก",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ข้อใดคือชื่อของหุ่นยนต์แมวสีฟ้าสุดฉลาดจากโลกอนาคตในการ์ตูนยอดนิยม?",
                "choice_a": "โดราเอมอน (Doraemon)",
                "choice_b": "โนบิตะ",
                "choice_c": "ชิซุกะ",
                "choice_d": "ไจแอนท์",
                "correct_choice": "A",
                "explanation": "โดราเอมอนเป็นหุ่นยนต์แมวจากศตวรรษที่ 22 ที่มีกระเป๋าวิเศษใส่ของไฮเทคมากมาย",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "คำว่า 'AI' หรือ ปัญญาประดิษฐ์ มีหน้าที่ช่วยเหลือมนุษย์อย่างไร?",
                "choice_a": "ช่วยคิด ตอบคำถาม ค้นหาข้อมูล และช่วยทำงานได้อย่างฉลาด",
                "choice_b": "กินข้าวเย็นแทนเรา",
                "choice_c": "นอนหลับแทนเรา",
                "choice_d": "อาบน้ำสระผมแทนเรา",
                "correct_choice": "A",
                "explanation": "AI เป็นเทคโนโลยีคอมพิวเตอร์ที่ถูกฝึกฝนให้คิดและช่วยตอบคำถามมนุษย์ได้อย่างรวดเร็ว",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "แป้นพิมพ์คอมพิวเตอร์ในประเทศไทย บนปุ่มมักสกรีนตัวหนังสือภาษาใดไว้คู่กัน?",
                "choice_a": "ภาษาไทย และ ภาษาอังกฤษ",
                "choice_b": "ภาษาต่างดาว และ ภาษาหุ่นยนต์",
                "choice_c": "ภาษาอียิปต์โบราณ",
                "choice_d": "ภาษาละตินโบราณ",
                "correct_choice": "A",
                "explanation": "คีย์บอร์ดไทยมีตัวอักษรไทย (ก-ฮ) และภาษาอังกฤษ (A-Z) สลับเปลี่ยนภาษาได้ง่าย",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ข้อใดคือสัตว์ที่มีชื่อและรูปเหมือนโปรแกรมเปิดเว็บชื่อดัง 'Firefox'?",
                "choice_a": "หมาจิ้งจอกสีส้ม (Red Panda / Fox)",
                "choice_b": "ฮิปโปโปเตมัส",
                "choice_c": "ยีราฟคอยาว",
                "choice_d": "ช้างแอฟริกา",
                "correct_choice": "A",
                "explanation": "Firefox มีโลโก้เป็นรูปหมาจิ้งจอกสีส้มโอบล้อมลูกโลกสีน้ำเงินอย่างสวยงาม",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "หูฟังไร้สายแบบบลูทูธ (Bluetooth) เชื่อมต่อกับโทรศัพท์มือถือด้วยสิ่งใด?",
                "choice_a": "คลื่นสัญญาณวิทยุไร้สาย (ไม่ต้องมีสาย)",
                "choice_b": "เชือกกล้วย",
                "choice_c": "หนังยางรัดแกง",
                "choice_d": "เทปกาวสองหน้า",
                "correct_choice": "A",
                "explanation": "Bluetooth ส่งสัญญาณเสียงผ่านคลื่นความถี่วิทยุไร้สายในระยะใกล้ได้อย่างสะดวกสบาย",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "หากหน้าจอคอมพิวเตอร์สว่างจ้าเกินไปจนแสบตา เราควรทำอย่างไรดีที่สุด?",
                "choice_a": "ปรับลดระดับความสว่างหน้าจอ (Brightness) ลงให้อยู่ในระดับพอดี",
                "choice_b": "ใส่แว่นตาดำแล้วนอนหลับ",
                "choice_c": "เอาผ้าห่มมาคลุมหัว",
                "choice_d": "ทุบหน้าจอทิ้ง",
                "correct_choice": "A",
                "explanation": "การปรับความสว่างหน้าจอให้พอดีกับแสงในห้องจะช่วยถนอมสายตาไม่ให้อ่อนล้า",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "สิ่งใดใช้ป้องกันไม่ให้คนแปลกหน้าแอบเปิดดูข้อมูลในโทรศัพท์มือถือของเรา?",
                "choice_a": "การตั้งรหัสผ่านล็อกหน้าจอ หรือ สแกนลายนิ้วมือ",
                "choice_b": "เอาเทปใสมาพันรอบเครื่อง",
                "choice_c": "เอาโทรศัพท์ไปซ่อนไว้ใต้หมอน",
                "choice_d": "เขียนป้ายแปะว่าห้ามจับ",
                "correct_choice": "A",
                "explanation": "รหัสผ่าน PIN หรือลายนิ้วมือช่วยป้องกันข้อมูลส่วนตัวไม่ให้ผู้อื่นเข้าถึงได้โดยไม่ได้รับอนุญาต",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "คำว่า 'ออนไลน์' (Online) ในการใช้คอมพิวเตอร์ หมายถึงอะไร?",
                "choice_a": "การเชื่อมต่อกับระบบเครือข่ายอินเทอร์เน็ต",
                "choice_b": "การยืนเข้าแถวเคารพธงชาติ",
                "choice_c": "การนอนหลับกลางวัน",
                "choice_d": "การวาดเส้นตรงลงในกระดาษ",
                "correct_choice": "A",
                "explanation": "Online หมายถึงสถานะที่เครื่องของเรากำลังเชื่อมต่อกับโลกอินเทอร์เน็ต",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "โปรแกรม 'เครื่องคิดเลข' (Calculator) บนคอมพิวเตอร์ มีประโยชน์อย่างไร?",
                "choice_a": "ช่วยคิดคำนวณ บวก ลบ คูณ หาร ตัวเลขได้อย่างแม่นยำ",
                "choice_b": "ร้องเพลงขับกล่อม",
                "choice_c": "วาดรูปสัตว์เลี้ยง",
                "choice_d": "ดูการพยากรณ์อากาศ",
                "correct_choice": "A",
                "explanation": "Calculator ช่วยคำนวณตัวเลขและคิดเลขยาก ๆ ได้ในเสี้ยววินาที",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ข้อใดคือสิ่งมหัศจรรย์ที่คอมพิวเตอร์ 'ทำไม่ได้' เหมือนมนุษย์?",
                "choice_a": "รู้สึกหิวข้าว หิวน้ำ หรือมีความรู้สึกเจ็บปวด",
                "choice_b": "คิดเลขอย่างรวดเร็ว",
                "choice_c": "เปิดเพลงให้ฟัง",
                "choice_d": "แสดงภาพการ์ตูนสีสันสดใส",
                "correct_choice": "A",
                "explanation": "คอมพิวเตอร์เป็นอุปกรณ์อิเล็กทรอนิกส์ ไม่มีชีวิต ไม่มีความรู้สึกหิวหรือเหนื่อยเหมือนมนุษย์",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ชิ้นส่วนใดทำหน้าที่เปรียบเหมือน 'สมอง' ของคอมพิวเตอร์ที่คอยคิดและประมวลผลคำสั่ง?",
                "choice_a": "ซีพียู (CPU)",
                "choice_b": "สายเมาส์",
                "choice_c": "ปลั๊กไฟพ่วง",
                "choice_d": "ผ้าปูโต๊ะ",
                "correct_choice": "A",
                "explanation": "CPU (Central Processing Unit) ทำหน้าที่คิดคำนวณและประมวลผลคำสั่งต่าง ๆ เปรียบเสมือนสมองของคอมพิวเตอร์",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ลำโพงคอมพิวเตอร์ทำหน้าที่ส่งสิ่งใดออกมาให้เราได้รับรู้ผ่านหู?",
                "choice_a": "คลื่นเสียง (Sound)",
                "choice_b": "กลิ่นหอมดอกไม้",
                "choice_c": "ลมหนาว",
                "choice_d": "แสงเลเซอร์หลากสี",
                "correct_choice": "A",
                "explanation": "ลำโพงแปลงสัญญาณไฟฟ้าให้กลายเป็นคลื่นเสียงเพลง เสียงเกม หรือเสียงพูด",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ปุ่ม 'Esc' (Escape) ที่มุมซ้ายบนสุดของคีย์บอร์ด มักใช้สำหรับทำอะไร?",
                "choice_a": "ยกเลิกคำสั่ง หรือ ออกจากโหมดแสดงผลเต็มหน้าจอ",
                "choice_b": "เปิดเพลงเต้น",
                "choice_c": "สั่งอาหารเดลิเวอรี",
                "choice_d": "ปิดไฟในห้องนอน",
                "correct_choice": "A",
                "explanation": "ปุ่ม Esc ย่อมาจาก Escape ใช้กดยกเลิกการทำงานหรือปิดหน้าต่างย่อย",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "เวลาพิมพ์ข้อความแล้วพิมพ์ตัวหนังสือผิด เราต้องทำอย่างไร?",
                "choice_a": "กดปุ่มลบ (Backspace) แล้วพิมพ์ตัวหนังสือที่ถูกต้องลงไปใหม่",
                "choice_b": "ซื้อคอมพิวเตอร์เครื่องใหม่ทันที",
                "choice_c": "นั่งร้องไห้",
                "choice_d": "ปิดหน้าจอวิ่งหนี",
                "correct_choice": "A",
                "explanation": "แค่กดปุ่ม Backspace ลบตัวที่พิมพ์ผิด แล้วกดแป้นพิมพ์ใหม่ได้ง่ายนิดเดียว",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "สาขาวิชาวิทยาการคอมพิวเตอร์ มหาวิทยาลัยราชภัฏศรีสะเกษ มีตัวย่อภาษาอังกฤษว่าอะไร?",
                "choice_a": "CS SSKRU",
                "choice_b": "ABC 123",
                "choice_c": "XYZ 999",
                "choice_d": "SOS 007",
                "correct_choice": "A",
                "explanation": "CS ย่อมาจาก Computer Science และ SSKRU ย่อมาจาก Sisaket Rajabhat University",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ถ้าน้อง ๆ อยากสร้างเกม สร้างเว็บไซต์ หรือพัฒนาแอปพลิเคชันในอนาคต ควรเลือกเรียนสาขาใด?",
                "choice_a": "วิทยาการคอมพิวเตอร์ (Computer Science)",
                "choice_b": "การขับรถบรรทุกดิน",
                "choice_c": "การต่อเสาไฟฟ้าแรงสูง",
                "choice_d": "การเลี้ยงปลาเงินปลาทอง",
                "correct_choice": "A",
                "explanation": "วิทยาการคอมพิวเตอร์สอนทักษะการเขียนโปรแกรมและการสร้างสรรค์เทคโนโลยีเพื่ออนาคต",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ข้อใดคือประโยชน์ของคอมพิวเตอร์ในการเรียนรู้ของเด็ก ๆ ในยุคปัจจุบัน?",
                "choice_a": "ค้นคว้าหาความรู้ ทำการบ้าน ทำรายงาน และฝึกทักษะใหม่ ๆ",
                "choice_b": "เอาไว้ตั้งโต๊ะเฉย ๆ ห้ามเปิด",
                "choice_c": "ใช้แทนหมอนหนุนนอนตอนกลางวัน",
                "choice_d": "ใช้เป็นที่วางแก้วน้ำ",
                "correct_choice": "A",
                "explanation": "คอมพิวเตอร์เปิดโลกการเรียนรู้ ช่วยให้เราค้นคว้าความรู้ได้ทั่วโลกอย่างไม่สิ้นสุด",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ถ้าโน้ตบุ๊กหรือโทรศัพท์มือถือแบตเตอรี่ใกล้จะหมด จะมีสิ่งใดปรากฏบนหน้าจอ?",
                "choice_a": "สัญลักษณ์รูปแบตเตอรี่แจ้งเตือนว่าเหลือพลังงานน้อย",
                "choice_b": "มีเสียงเป่านกหวีดดังลั่นห้อง",
                "choice_c": "ตัวเครื่องจะหมุนรอบตัวเอง",
                "choice_d": "หน้าจอจะหลุดหล่นลงมา",
                "correct_choice": "A",
                "explanation": "ระบบจะแสดงไอคอนแบตเตอรี่สีแดงหรือข้อความเตือนให้เราเสียบสายชาร์จ",
                "difficulty": "ง่าย",
                "is_active": True,
            },
            {
                "category": cat_cs,
                "text": "ทุกคนที่มาร่วมสนุกกับกิจกรรม 'CS Random Quiz' วันนี้ จะได้รับสิ่งใดกลับไป?",
                "choice_a": "รอยยิ้ม ความสนุกสนาน เสียงหัวเราะ และความรู้ไอที!",
                "choice_b": "การบ้านเพิ่ม 1,000 หน้า",
                "choice_c": "การโดนคุณครูทำโทษ",
                "choice_d": "ความง่วงนอน",
                "correct_choice": "A",
                "explanation": "CS Random Quiz สร้างขึ้นเพื่อให้ทุกคนได้สนุกสนาน ผ่อนคลาย และได้ความรู้ไปพร้อม ๆ กัน 🎉",
                "difficulty": "ง่าย",
                "is_active": True,
            }
        ]

        # เพิ่มลงฐานข้อมูล
        from my_app.firebase_config import sync_question_to_firestore, is_firebase_connected
        
        firebase_online = is_firebase_connected()
        if firebase_online:
            self.stdout.write(self.style.NOTICE("[Firebase] Connected to Cloud Firestore. Syncing questions..."))

        count = 0
        for q_data in questions:
            q = Question.objects.create(**q_data)
            if firebase_online:
                sync_question_to_firestore(q)
            count += 1

        self.stdout.write(self.style.SUCCESS(f"[SUCCESS] Reseeded {count} super easy and fun questions successfully!"))
        if firebase_online:
            self.stdout.write(self.style.SUCCESS("[Firebase] Synced all 50 questions to Firebase Cloud Firestore!"))
